# Generated by Django 5.1.7 on 2025-04-03 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau_requis', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=False)),
                ('derniere_consultation', models.DateTimeField(blank=True, null=True)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets_connectes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
