# Generated by Django 5.1.7 on 2025-04-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objets_connectes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objetconnecte",
            name="utilisateur",
        ),
    ]
