# Generated by Django 5.1.7 on 2025-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets_connectes", "0002_remove_objetconnecte_utilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="consommation",
            field=models.PositiveIntegerField(
                default=100, help_text="Consommation en Watt-heure"
            ),
            preserve_default=False,
        ),
    ]
