# Generated by Django 5.1.7 on 2025-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets_connectes", "0003_objetconnecte_consommation"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="consommation_totale",
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
                help_text="Consommation totale de l'objet en Watt-heure",
            ),
        ),
    ]
