# Generated by Django 5.1.7 on 2025-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objets_connectes", "0004_objetconnecte_consommation_totale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetconnecte",
            name="consommation",
            field=models.FloatField(help_text="Consommation en Watt-heure"),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="consommation_totale",
            field=models.FloatField(
                default=0, help_text="Consommation totale de l'objet en Watt-heure"
            ),
        ),
    ]
