# Generated by Django 5.1.7 on 2025-04-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets_connectes', '0005_alter_objetconnecte_consommation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetconnecte',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Température en °C (uniquement pour frigo et four)', null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='type_objet',
            field=models.CharField(choices=[('camera', 'Caméra'), ('frigo', 'Frigo'), ('four', 'Four')], default='camera', max_length=10),
        ),
        migrations.AlterField(
            model_name='objetconnecte',
            name='consommation_totale',
            field=models.FloatField(default=0, help_text="Consommation totale de l'objet"),
        ),
    ]
