# Generated by Django 5.1.7 on 2025-04-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objets_connectes', '0006_objetconnecte_temperature_objetconnecte_type_objet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetconnecte',
            name='consommation_totale',
        ),
    ]
