# Generated by Django 4.2.20 on 2025-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets_connectes', '0007_remove_objetconnecte_consommation_totale'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetconnecte',
            name='nombre_consultations',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de consultations'),
        ),
    ]
