# Generated by Django 4.2.20 on 2025-04-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objets_connectes', '0008_objetconnecte_nombre_consultations'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetconnecte',
            name='nombre_utilisations',
            field=models.PositiveIntegerField(default=0, help_text="Nombre total d'activations/désactivations"),
        ),
    ]
