# Generated by Django 5.1.7 on 2025-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="url_onclick",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
