# Generated by Django 5.1.7 on 2025-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_section_url_onclick"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="url_onclick",
            new_name="view_onclick",
        ),
        migrations.AddField(
            model_name="section",
            name="view_param_onclick",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
