# Generated by Django 5.1.7 on 2025-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_rename_url_onclick_section_view_onclick_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="priorite",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paragraphe",
            name="priorite",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="section",
            name="priorite",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
