# Generated by Django 5.1.7 on 2025-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0004_image_priorite_paragraphe_priorite_section_priorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="legende",
            field=models.TextField(blank=True, null=True),
        ),
    ]
