# Generated by Django 5.1.7 on 2025-03-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
