# Generated by Django 5.1.7 on 2025-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="titre",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
