# Generated by Django 5.1.7 on 2025-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0002_evenement_slug_alter_evenement_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
