# Generated by Django 5.1.7 on 2025-04-03 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0003_alter_evenement_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "evenement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evenements.evenement",
                    ),
                ),
            ],
            bases=("evenements.evenement",),
        ),
        migrations.AddField(
            model_name="evenement",
            name="debut",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 4, 3, 13, 33, 45, 947647, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evenement",
            name="email",
            field=models.EmailField(default="defaultmail@mail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evenement",
            name="etat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evenement",
            name="fin",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 4, 3, 13, 34, 44, 311849, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date",
            field=models.DateField(),
        ),
    ]
