# Generated by Django 5.1.7 on 2025-04-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "evenements",
            "0004_meta_evenement_debut_evenement_email_evenement_etat_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="evenement",
            old_name="etat",
            new_name="est_valide",
        ),
    ]
