# Generated by Django 5.1.7 on 2025-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0005_rename_etat_evenement_est_valide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
