# Generated by Django 4.2.20 on 2025-04-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonModele',
            new_name='Historique',
        ),
    ]
