# Generated by Django 4.2.20 on 2025-04-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historique', '0002_rename_monmodele_historique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historique',
            old_name='date_creation',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nom',
        ),
        migrations.AddField(
            model_name='historique',
            name='action',
            field=models.TextField(default='Action par défaut'),
        ),
        migrations.AddField(
            model_name='historique',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
