# Generated by Django 4.2.20 on 2025-04-06 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historique', '0003_rename_date_creation_historique_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historique',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to=settings.AUTH_USER_MODEL),
        ),
    ]
