# Generated by Django 5.1.7 on 2025-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
