# Generated by Django 5.1.7 on 2025-03-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0003_category_restaurant_menuitem_category_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
