# Generated by Django 5.1.7 on 2025-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0005_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="verification_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
