# Generated by Django 5.1.7 on 2025-04-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_emailverification_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
