# Generated by Django 5.1.7 on 2025-04-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_utilisateur_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='type_personne',
            field=models.CharField(choices=[('Serveur', 'Serveur'), ('Chef', 'Chef'), ('Client', 'Client')], default='Client', max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
