# Generated by Django 5.1.7 on 2025-04-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_categorieboisson_categorieplat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accompagnementboisson",
            name="plat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.boisson"
            ),
        ),
        migrations.AlterField(
            model_name="varianteboisson",
            name="plat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.boisson"
            ),
        ),
    ]
