# Generated by Django 5.1.7 on 2025-04-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_accompagnementboisson_plat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accompagnementboisson",
            old_name="plat",
            new_name="boisson",
        ),
        migrations.RenameField(
            model_name="varianteboisson",
            old_name="plat",
            new_name="boisson",
        ),
    ]
