# Generated by Django 5.1.7 on 2025-04-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_rename_plat_accompagnementboisson_boisson_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="varianteplat",
            name="plat",
        ),
        migrations.DeleteModel(
            name="VarianteBoisson",
        ),
        migrations.DeleteModel(
            name="VariantePlat",
        ),
    ]
