# Generated by Django 5.1.7 on 2025-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_remove_varianteplat_plat_delete_varianteboisson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boisson",
            name="prixBouteille",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
