# Generated by Django 5.1.7 on 2025-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_boisson_prixbouteille"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
