# Generated by Django 5.1.7 on 2025-04-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_menu_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="titre",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
